// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwCSkYQIruTmJrqYOnLe0jYJt7gFPvic',
    appId: '1:798628585570:web:3f6ff6753a0dc305c1b13b',
    messagingSenderId: '798628585570',
    projectId: 'todo-analytics-demo',
    authDomain: 'todo-analytics-demo.firebaseapp.com',
    storageBucket: 'todo-analytics-demo.firebasestorage.app',
    measurementId: 'G-GNF611LNBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOp0L8fNLPSDQXSM7NK6PDHP33zZkg2Fc',
    appId: '1:798628585570:android:2b3f5bb258c45328c1b13b',
    messagingSenderId: '798628585570',
    projectId: 'todo-analytics-demo',
    storageBucket: 'todo-analytics-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhaCNuWg9Tc6-FyTjL7JiL7RTR3ND0Cs',
    appId: '1:798628585570:ios:41e8e5f55f58a5c5c1b13b',
    messagingSenderId: '798628585570',
    projectId: 'todo-analytics-demo',
    storageBucket: 'todo-analytics-demo.firebasestorage.app',
    iosBundleId: 'com.example.todoAnalyticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvhaCNuWg9Tc6-FyTjL7JiL7RTR3ND0Cs',
    appId: '1:798628585570:ios:41e8e5f55f58a5c5c1b13b',
    messagingSenderId: '798628585570',
    projectId: 'todo-analytics-demo',
    storageBucket: 'todo-analytics-demo.firebasestorage.app',
    iosBundleId: 'com.example.todoAnalyticsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMwCSkYQIruTmJrqYOnLe0jYJt7gFPvic',
    appId: '1:798628585570:web:0afe0f673ac01507c1b13b',
    messagingSenderId: '798628585570',
    projectId: 'todo-analytics-demo',
    authDomain: 'todo-analytics-demo.firebaseapp.com',
    storageBucket: 'todo-analytics-demo.firebasestorage.app',
    measurementId: 'G-PVTLWGTTHG',
  );
}
